#!/usr/bin/env bash

# https://github.com/mierak/rmpc

REPO_ROOT="$(git rev-parse --show-toplevel)"
pushd "$REPO_ROOT" || exit 1

if [ -d "rmpc" ]; then
    pushd rmpc || exit 1
    git pull
    popd || exit 1
else
    git clone https://github.com/mierak/rmpc
fi

popd || exit 1
